databases:
    - name: commercedb
      plan: free
      databaseName: commerce
      user: commerce

services:
    - type: web
      plan: free
      name: commerce
      runtime: python
      buildCommand: "./build.sh"
      startCommand: "python -m gunicorn commerce.asgi:application -k uvicorn.workers.UvicornWorker"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: commercedb
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
